-- Server Objects


--AXE
includeFile("weapon/post_14/melee/axe_heavy_duty_npe.lua")


--SPECIAL
includeFile("weapon/post_14/melee/blacksun_razor_generic.lua")
includeFile("weapon/post_14/melee/blasterfist.lua")
includeFile("weapon/post_14/melee/blasterfist_generic.lua")
includeFile("weapon/post_14/melee/ep3_loot_heartstriker.lua")
includeFile("weapon/post_14/melee/ep3_loot_necrosis.lua")
includeFile("weapon/post_14/melee/ep3_loot_soulstinger.lua")
includeFile("weapon/post_14/melee/fan_metal.lua")
includeFile("weapon/post_14/melee/massassiknuckler.lua")
includeFile("weapon/post_14/melee/punch_dagger.lua")
includeFile("weapon/post_14/melee/pvp_bf_knuckler.lua")
includeFile("weapon/post_14/melee/vibroknuckler_npe.lua")
includeFile("weapon/post_14/melee/vibroknuckler_static.lua")
includeFile("weapon/post_14/melee/wod_war_fan.lua")
includeFile("weapon/post_14/melee/wookiee_knuckler_wod.lua")
includeFile("weapon/post_14/melee/wookiee_knuckler.lua")


--POLEARM
includeFile("weapon/post_14/melee/ep3_loot_pestilence_wod.lua")
includeFile("weapon/post_14/melee/ep3_loot_pestilence.lua")
includeFile("weapon/post_14/melee/ep3_loot_poisonspike.lua")
includeFile("weapon/post_14/melee/ep3_loot_strike.lua")
includeFile("weapon/post_14/melee/lance_avatar_wke_heartlance.lua")
includeFile("weapon/post_14/melee/lance_controllerfp_npe.lua")
includeFile("weapon/post_14/melee/lance_cryo.lua")
includeFile("weapon/post_14/melee/lance_electric_polearm.lua")
includeFile("weapon/post_14/melee/lance_gcw_gand_shockprod.lua")
includeFile("weapon/post_14/melee/lance_kaminoan.lua")
includeFile("weapon/post_14/melee/lance_kaminoan_generic.lua")
includeFile("weapon/post_14/melee/lance_kashyyk.lua")
includeFile("weapon/post_14/melee/lance_kashyyk_generic.lua")
includeFile("weapon/post_14/melee/lance_massassi.lua")
includeFile("weapon/post_14/melee/lance_nightsister_legendary.lua")
includeFile("weapon/post_14/melee/lance_shock.lua")
includeFile("weapon/post_14/melee/lance_staff_magna_guard.lua")
includeFile("weapon/post_14/melee/lance_staff_wood_s1_npe.lua")
includeFile("weapon/post_14/melee/lance_staff_wood_s2_npe.lua")
includeFile("weapon/post_14/melee/lance_wod_twin_blade.lua")
includeFile("weapon/post_14/melee/polearm_heroic_sd.lua")
includeFile("weapon/post_14/melee/polearm_lance_electric_polearm.lua")
includeFile("weapon/post_14/melee/polearm_vibro_axe_npe.lua")
includeFile("weapon/post_14/melee/som_lance_obsidian.lua")
includeFile("weapon/post_14/melee/som_lance_obsidian_generic.lua")
includeFile("weapon/post_14/melee/som_lance_xandank.lua")
includeFile("weapon/post_14/melee/som_lance_xandank_generic.lua")
includeFile("weapon/post_14/melee/lance_trando.lua")
includeFile("weapon/post_14/melee/lance_wookiee.lua")

--POLEARM/CRAFTED_SABER
includeFile("weapon/post_14/melee/sword_lightsaber_polearm_gen4_heroic.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_polearm_gen4_heroic_s02.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_polearm_gen5.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_polearm_pvp_bf.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_polearm_pvp_bf_gen5.lua")


--2H SWORD
includeFile("weapon/post_14/melee/2h_sword_avatar_wke_toothpick.lua")
includeFile("weapon/post_14/melee/2h_sword_avatar_wke_toothpick2.lua")
includeFile("weapon/post_14/melee/2h_sword_battleaxe_npe.lua")
includeFile("weapon/post_14/melee/2h_sword_battleaxe_quest.lua")
includeFile("weapon/post_14/melee/2h_sword_cleaver_npe.lua")
includeFile("weapon/post_14/melee/2h_sword_kashyyk.lua")
includeFile("weapon/post_14/melee/2h_sword_kashyyk_wod.lua")
includeFile("weapon/post_14/melee/2h_sword_katana_generic.lua")
includeFile("weapon/post_14/melee/2h_sword_kun_massassi.lua")
includeFile("weapon/post_14/melee/2h_sword_maul_legendary.lua")
includeFile("weapon/post_14/melee/2h_sword_pvp_bf_01.lua")
includeFile("weapon/post_14/melee/2h_sword_sith.lua")
includeFile("weapon/post_14/melee/2h_sword_sith_generic.lua")
includeFile("weapon/post_14/melee/2h_sword_sith_wod.lua")
includeFile("weapon/post_14/melee/2h_sword_wod_scyth.lua")
includeFile("weapon/post_14/melee/2h_sword_wod_sword.lua")
includeFile("weapon/post_14/melee/ep3_loot_executer.lua")
includeFile("weapon/post_14/melee/ep3_loot_lifeblood.lua")
includeFile("weapon/post_14/melee/ep3_loot_sickle.lua")
includeFile("weapon/post_14/melee/ep3_loot_sickle_wod.lua")
includeFile("weapon/post_14/melee/quest_2h_sword_battleaxe.lua")
includeFile("weapon/post_14/melee/quest_2h_sword_maul.lua")
includeFile("weapon/post_14/melee/som_2h_sword_massassi.lua")
includeFile("weapon/post_14/melee/som_2h_sword_obsidian.lua")
includeFile("weapon/post_14/melee/som_2h_sword_obsidian_generic.lua")
includeFile("weapon/post_14/melee/som_2h_sword_tulrus.lua")
includeFile("weapon/post_14/melee/som_2h_sword_tulrus_generic.lua")


--2H SWORD/CRAFTED_SABER
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_gcw_s01_gen4.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_gcw_s01_gen5.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_gen4_must.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_gen5.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_gen5_eow.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_gen5_sith.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_pvp_bf.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_two_handed_pvp_bf_gen5.lua")


--BATON
includeFile("weapon/post_14/melee/baton_avatar_trando_stun_stick.lua")
includeFile("weapon/post_14/melee/baton_gaderiffi_elite.lua")
includeFile("weapon/post_14/melee/baton_gaderiffi_npe.lua")
includeFile("weapon/post_14/melee/baton_stun_legendary.lua")
includeFile("weapon/post_14/melee/mandoviol_smasher.lua")
includeFile("weapon/post_14/melee/xantha_smasher.lua")


--KNIFE
includeFile("weapon/post_14/melee/ep3_loot_blackbane.lua")
includeFile("weapon/post_14/melee/knife_dagger_static.lua")
includeFile("weapon/post_14/melee/knife_survival_decorative.lua")
includeFile("weapon/post_14/melee/knife_survival_npe.lua")
includeFile("weapon/post_14/melee/knife_naktra_crystal.lua")
includeFile("weapon/post_14/melee/knife_trando_skinner.lua")


--SWORD
includeFile("weapon/post_14/melee/ep3_loot_eventide.lua")
includeFile("weapon/post_14/melee/ep3_loot_ripper.lua")
includeFile("weapon/post_14/melee/ep3_loot_ripper_wod.lua")
includeFile("weapon/post_14/melee/som_sword_mustafar_bandit.lua")
includeFile("weapon/post_14/melee/som_sword_mustafar_bandit_generic.lua")
includeFile("weapon/post_14/melee/som_sword_obsidian.lua")
includeFile("weapon/post_14/melee/som_sword_obsidian_generic.lua")
includeFile("weapon/post_14/melee/sword_01_npe.lua")
includeFile("weapon/post_14/melee/sword_01_static.lua")
includeFile("weapon/post_14/melee/sword_02_generic.lua")
includeFile("weapon/post_14/melee/sword_acid.lua")
includeFile("weapon/post_14/melee/sword_avatar_wke_spiritblade.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_adeen.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_umakk.lua")
includeFile("weapon/post_14/melee/sword_mace_junti.lua")
includeFile("weapon/post_14/melee/sword_mace_junti_generic.lua")
includeFile("weapon/post_14/melee/sword_mandalorian.lua")
includeFile("weapon/post_14/melee/sword_marauder.lua")
includeFile("weapon/post_14/melee/sword_massassi.lua")
includeFile("weapon/post_14/melee/sword_massassi_generic.lua")
includeFile("weapon/post_14/melee/sword_pvp_bf_01.lua")
includeFile("weapon/post_14/melee/sword_rantok_generic.lua")
includeFile("weapon/post_14/melee/sword_rebel.lua")
includeFile("weapon/post_14/melee/sword_rsf.lua")
includeFile("weapon/post_14/melee/sword_rsf_generic.lua")
includeFile("weapon/post_14/melee/sword_wod_scyth.lua")
includeFile("weapon/post_14/melee/sword_wod_sword.lua")
includeFile("weapon/post_14/melee/sword_wookiee.lua")
--includeFile("weapon/post_14/ep3/sword_wookiee.lua")


--SWORD/CRAFTED_SABER
includeFile("weapon/post_14/melee/generic_sword_lightsaber_one_handed_gen1.lua")
includeFile("weapon/post_14/melee/generic_sword_lightsaber_training.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_mandalorian.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_one_handed_gcw_s01_gen4.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_one_handed_gcw_s01_gen5.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_one_handed_gen1_s02.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_one_handed_gen4_must.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_one_handed_pvp_bf.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_one_handed_pvp_bf_gen5.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_ranged_donotuse_s01.lua")
includeFile("weapon/post_14/melee/sword_lightsaber_ranged_donotuse_s02.lua")
