				"CU Melee Weapons",
				{
					"2H Kashyyyk Sword", "object/weapon/melee/2h_sword/2h_sword_kashyyk.iff",
					"2H Sith Sword", "object/weapon/melee/2h_sword/2h_sword_sith.iff",
					"Blasterfist", "object/weapon/melee/special/blasterfist.iff",
					"Naktra Crystal Knife", "object/weapon/melee/knife/ep3/knife_naktra_crystal.iff",
					"Trandoshan Skinner Knife", "object/weapon/melee/knife/ep3/knife_trando_skinner.iff",
					"Cryo Lance", "object/weapon/melee/polearm/lance_cryo.iff",
					"Electric Polearm", "object/weapon/melee/polearm/lance_electric_polearm.iff",
					"Kaminoan Lance", "object/weapon/melee/polearm/lance_kaminoan.iff",
					"Kashyyyk Lance", "object/weapon/melee/polearm/lance_kashyyk.iff",
					"Massassi Lance", "object/weapon/melee/polearm/lance_massassi.iff",
					"Shock Lance", "object/weapon/melee/polearm/lance_shock.iff",
					"Trandoshan Lance", "object/weapon/melee/polearm/ep3/lance_trando.iff",
					"Wookie Lance", "object/weapon/melee/polearm/ep3/lance_wookiee.iff",
					"Massassi Knuckler", "object/weapon/melee/special/massassiknuckler.iff",
					"Electric Polearm Lance", "object/weapon/melee/polearm/polearm_lance_electric_polearm.iff",
					"Acid Sword", "object/weapon/melee/sword/sword_acid.iff",
					"Junti Mace", "object/weapon/melee/sword/sword_mace_junti.iff",
					"Marauder Sword", "object/weapon/melee/sword/sword_marauder.iff",
					"Massassi Sword", "object/weapon/melee/sword/sword_massassi.iff",
					"RSF Sword", "object/weapon/melee/sword/sword_rsf.iff",
					"Wookiee Sword", "object/weapon/melee/sword/ep3/sword_wookiee.iff",
					"Wookiee Knuckler", "object/weapon/melee/special/ep3/wookiee_knuckler.iff"
				},
				"CU Ranged Weapons",
				{
					"Alliance Needler Carbine", "object/weapon/ranged/carbine/carbine_alliance_needler.iff",
					"Bothan Bola Carbine", "object/weapon/ranged/carbine/carbine_bothan_bola.iff",
					"Czerka Dart", "object/weapon/ranged/carbine/carbine_czerka_dart.iff",
					"DC15 Carbine", "object/weapon/ranged/carbine/ep3/carbine_dc15.iff",
					"Geo Carbine", "object/weapon/ranged/carbine/carbine_geo.iff",
					"Proton Carbine", "object/weapon/ranged/carbine/carbine_proton.iff",
					"Rotary Underslung Carbine", "object/weapon/ranged/carbine/carbine_rotary_underslung.iff",	
					"Underslung Carbine", "object/weapon/ranged/carbine/carbine_underslung.iff",
					"Wookie Bowcaster Carbine", "object/weapon/ranged/carbine/ep3/carbine_wookiee_bowcaster.iff",
					"Deathhammer Pistol", "object/weapon/ranged/pistol/pistol_deathhammer.iff",
					"Flare Pistol", "object/weapon/ranged/pistol/pistol_flare.iff",
					"Intimidator Pistol", "object/weapon/ranged/pistol/pistol_intimidator.iff",
					"Ion Stunner Pistol", "object/weapon/ranged/pistol/ep3/pistol_ion_stunner.iff",
					"Jawa Pistol", "object/weapon/ranged/pistol/pistol_jawa.iff",
					"KYD21 Pistol", "object/weapon/ranged/pistol/ep3/pistol_kyd21.iff",
					"Renegade Pistol", "object/weapon/ranged/pistol/pistol_renegade.iff",
					"Trando Surpressor Pistol", "object/weapon/ranged/pistol/ep3/pistol_trando_suppressor.iff",
					"Wookiee Pistol", "object/weapon/ranged/pistol/ep3/pistol_wookiee.iff",
					"Wookiee Bowcaster Pistol", "object/weapon/ranged/pistol/ep3/pistol_wookiee_bowcaster.iff",
					"Adventurer Rifle", "object/weapon/ranged/rifle/rifle_adventurer.iff",
					"Heavy Bowcaster Rifle", "object/weapon/ranged/rifle/rifle_bowcaster_heavy.iff",
					"Medium Bowcaster Rifle", "object/weapon/ranged/rifle/rifle_bowcaster_medium.iff",
					"DC15 Rifle", "object/weapon/ranged/rifle/ep3/rifle_dc15.iff",
					"Geo Drill Rifle", "object/weapon/ranged/rifle/rifle_geo_drill.iff",
					"LD1 Rifle", "object/weapon/ranged/rifle/rifle_ld1.iff",
					"Massassi Ink Rifle", "object/weapon/ranged/rifle/rifle_massassi_ink.iff",
					"Naktra Crystal Rifle", "object/weapon/ranged/rifle/ep3/rifle_naktra_crystal.iff",
					"Proton Rifle", "object/weapon/ranged/rifle/rifle_proton.iff",
					"Trando Hunter Rifle", "object/weapon/ranged/rifle/ep3/rifle_trando_hunter.iff"
