object_mobile_ep3_ep3_blackscale_dead_03 = object_mobile_ep3_shared_ep3_blackscale_dead_03:new {
}
ObjectTemplates:addTemplate(object_mobile_ep3_ep3_blackscale_dead_03, "object/mobile/ep3/ep3_blackscale_dead_03.iff")
