object_mobile_ep3_ep3_blackscale_assault_m_03 = object_mobile_ep3_shared_ep3_blackscale_assault_m_03:new {
}
ObjectTemplates:addTemplate(object_mobile_ep3_ep3_blackscale_assault_m_03, "object/mobile/ep3/ep3_blackscale_assault_m_03.iff")
